<a href="https://colab.research.google.com/github/priyankkumar218/MISC/blob/master/ML2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing on a Small Dataset

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

1. Get the Data

In [0]:
dataset = pd.read_csv('https://raw.githubusercontent.com/iamrahul29/Weekend-Batch-Coding-Examples/master/Data_Pre.csv')

In [4]:
dataset

Age  Systolic Blood Pressure      State Diabetic
0  39.0                    144.0         UP       No
1  47.0                    220.0         MP      Yes
2  45.0                      NaN     Kerala       No
3  47.0                    145.0         UP       No
4  65.0                    162.0         MP      Yes
5   NaN                    142.0         MP       No
6  67.0                    170.0     Kerala      Yes
7  42.0                    124.0  Rajasthan       No
8  67.0                    158.0         MP      Yes
9  56.0                    154.0         UP       No

2. Discovery and Visualization: Since this is a very small dataset. No poit visualizing it.

3. Data Preprocessing

In [0]:
X = dataset.iloc[:, 0:3].values
y = dataset.iloc[:, -1].values

In [6]:
X

array([[39.0, 144.0, 'UP'],
       [47.0, 220.0, 'MP'],
       [45.0, nan, 'Kerala'],
       [47.0, 145.0, 'UP'],
       [65.0, 162.0, 'MP'],
       [nan, 142.0, 'MP'],
       [67.0, 170.0, 'Kerala'],
       [42.0, 124.0, 'Rajasthan'],
       [67.0, 158.0, 'MP'],
       [56.0, 154.0, 'UP']], dtype=object)

In [7]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No'],
      dtype=object)

In [0]:
# from sklearn.preprocessing import SimpleImputer # Deprecated
from sklearn.impute import SimpleImputer

In [0]:
sim = SimpleImputer(missing_values=np.nan, strategy='median') # mean can also be used here

In [11]:
sim.fit(X[:, 0:2])

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='median', verbose=0)

In [12]:
sim.statistics_

array([ 47., 154.])

In [0]:
X[:, 0:2] = sim.transform(X[:, 0:2])

In [16]:
X

array([[39.0, 144.0, 'UP'],
       [47.0, 220.0, 'MP'],
       [45.0, 154.0, 'Kerala'],
       [47.0, 145.0, 'UP'],
       [65.0, 162.0, 'MP'],
       [47.0, 142.0, 'MP'],
       [67.0, 170.0, 'Kerala'],
       [42.0, 124.0, 'Rajasthan'],
       [67.0, 158.0, 'MP'],
       [56.0, 154.0, 'UP']], dtype=object)

In [0]:
# Label Encoding of state in X and Diabetic in y
from sklearn.preprocessing import LabelEncoder

In [0]:
lab = LabelEncoder()

In [0]:
X[:,2] = lab.fit_transform(X[:, 2])

In [0]:
y =  lab.fit_transform(y)

In [21]:
lab.classes_

array(['No', 'Yes'], dtype=object)

In [0]:
# To remove Dummy Variable Trap
# One hot encode
dataset1 = pd.get_dummies(dataset)

In [23]:
dataset1

Age  Systolic Blood Pressure  ...  Diabetic_No  Diabetic_Yes
0  39.0                    144.0  ...            1             0
1  47.0                    220.0  ...            0             1
2  45.0                      NaN  ...            1             0
3  47.0                    145.0  ...            1             0
4  65.0                    162.0  ...            0             1
5   NaN                    142.0  ...            1             0
6  67.0                    170.0  ...            0             1
7  42.0                    124.0  ...            1             0
8  67.0                    158.0  ...            0             1
9  56.0                    154.0  ...            1             0

[10 rows x 8 columns]